version: "3.8"
services:
  database:
    image: mysql:5.7
    networks:
      - webnet
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_ROOT_PASSWORD: R1234r
  websrv:
    build: .
    depends_on:
      - database
    ports:
      - "80:80"
    restart: always
    networks:
      - webnet
networks:
  webnet:
    driver: bridge

  